// This is the checked-in Phase 2 subset. Replace it with the complete file
// generated by `supabase gen types typescript` after the project is linked.
export type ProfileRow = {
  id: string;
  display_name: string;
  share_code: string;
  avatar_path: string | null;
  created_at: string;
  updated_at: string;
};

export type ScenarioRow = {
  id: string;
  owner_id: string;
  title: string;
  system: string | null;
  scenario_type: "normal" | "campaign" | "kp_less";
  author: string | null;
  stage: string | null;
  title_reading: string | null;
  author_reading: string | null;
  recommended_skills: string | null;
  secondary_skills: string | null;
  not_recommended: string | null;
  lost_rate: "none" | "low" | "medium" | "high" | "very_high" | "unknown" | null;
  lost_rate_note: string | null;
  ho_type: "none" | "common" | "individual" | "secret" | "common_individual" | "special" | null;
  player_count_type: "fixed" | "range" | "free";
  player_count_fixed: number | null;
  player_count_min: number | null;
  player_count_max: number | null;
  player_count_text: string | null;
  play_time_type: "fixed" | "range" | "free";
  play_time_fixed: number | null;
  play_time_min: number | null;
  play_time_max: number | null;
  play_time_text: string | null;
  scenario_tags: string[];
  battle: "yes" | "no" | "conditional" | null;
  cautions: string | null;
  trailer_text: string | null;
  created_at: string;
  updated_at: string;
  legacy_registration: Record<string, unknown>;
};

export type ScenarioHandoutRow = {
  id: string;
  scenario_id: string;
  display_order: number;
  label: string | null;
  content: string;
  created_at: string;
  updated_at: string;
};

export type ScenarioEpisodeRow = {
  id: string;
  scenario_id: string;
  episode_number: number;
  title: string | null;
  time_type: "fixed" | "range" | "free";
  time_fixed: number | null;
  time_min: number | null;
  time_max: number | null;
  time_text: string | null;
  summary: string | null;
  status: "not_started" | "completed";
  play_date: string | null;
  created_at: string;
  updated_at: string;
  legacy_time_text: string | null;
};

export type ScenarioImageRow = {
  id: string;
  scenario_id: string;
  storage_path: string;
  display_order: number;
  created_at: string;
  updated_at: string;
  position_x: number;
  position_y: number;
  zoom: number;
};

export type ScenarioSessionRow = {
  id: string;
  scenario_id: string;
  display_order: number;
  name: string | null;
  role: "KP" | "PL";
  created_at: string;
  updated_at: string;
};

export type ScenarioSessionCharacterRow = {
  id: string;
  session_id: string;
  display_order: number;
  name: string | null;
  player_name: string | null;
  iachara_url: string | null;
  ho: string | null;
  memo: string | null;
  portrait_storage_path: string | null;
  created_at: string;
  updated_at: string;
};

export type UserScenarioDataRow = {
  id: string;
  user_id: string;
  scenario_id: string;
  favorite: boolean;
  kp_status: "not_started" | "completed";
  play_status: "not_started" | "completed";
  purchase_url: string | null;
  memo: string | null;
  kp_memo: string | null;
  pl_memo: string | null;
};

export type ScenarioDraftRow = {
  id: string;
  owner_id: string;
  scenario_id: string | null;
  title: string;
  payload: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

export type UserSettingsRow = {
  user_id: string;
  theme: "light" | "gray" | "dark";
  list_columns: number;
  delete_confirm: boolean;
  backup_after_save: boolean;
  discord_format: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

type ScenarioShareRow = {
  id: string;
  scenario_id: string;
  shared_user_id: string;
  permission: "viewer";
  created_at: string;
  updated_at: string;
};

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: Pick<ProfileRow, "id" | "display_name" | "share_code"> &
          Partial<Pick<ProfileRow, "avatar_path" | "created_at" | "updated_at">>;
        Update: Partial<
          Pick<ProfileRow, "display_name" | "share_code" | "avatar_path" | "updated_at">
        >;
        Relationships: [];
      };
      scenarios: {
        Row: ScenarioRow;
        Insert: Omit<ScenarioRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioRow>;
        Relationships: [];
      };
      user_scenario_data: {
        Row: UserScenarioDataRow;
        Insert: Omit<UserScenarioDataRow, "id" | "purchase_url" | "memo" | "kp_memo" | "pl_memo"> &
          Partial<Pick<UserScenarioDataRow, "purchase_url" | "memo" | "kp_memo" | "pl_memo">>;
        Update: Partial<UserScenarioDataRow>;
        Relationships: [];
      };
      scenario_shares: {
        Row: ScenarioShareRow;
        Insert: Omit<ScenarioShareRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioShareRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioShareRow>;
        Relationships: [];
      };
      scenario_handouts: {
        Row: ScenarioHandoutRow;
        Insert: Omit<ScenarioHandoutRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioHandoutRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioHandoutRow>;
        Relationships: [];
      };
      scenario_episodes: {
        Row: ScenarioEpisodeRow;
        Insert: Omit<ScenarioEpisodeRow, "id" | "created_at" | "updated_at" | "legacy_time_text"> &
          Partial<
            Pick<ScenarioEpisodeRow, "id" | "created_at" | "updated_at" | "legacy_time_text">
          >;
        Update: Partial<ScenarioEpisodeRow>;
        Relationships: [];
      };
      scenario_images: {
        Row: ScenarioImageRow;
        Insert: Omit<
          ScenarioImageRow,
          "id" | "created_at" | "updated_at" | "position_x" | "position_y" | "zoom"
        > &
          Partial<
            Pick<
              ScenarioImageRow,
              "id" | "created_at" | "updated_at" | "position_x" | "position_y" | "zoom"
            >
          >;
        Update: Partial<ScenarioImageRow>;
        Relationships: [];
      };
      scenario_sessions: {
        Row: ScenarioSessionRow;
        Insert: Omit<ScenarioSessionRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioSessionRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioSessionRow>;
        Relationships: [];
      };
      scenario_session_characters: {
        Row: ScenarioSessionCharacterRow;
        Insert: Omit<ScenarioSessionCharacterRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioSessionCharacterRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioSessionCharacterRow>;
        Relationships: [];
      };
      scenario_drafts: {
        Row: ScenarioDraftRow;
        Insert: Omit<ScenarioDraftRow, "id" | "created_at" | "updated_at"> &
          Partial<Pick<ScenarioDraftRow, "id" | "created_at" | "updated_at">>;
        Update: Partial<ScenarioDraftRow>;
        Relationships: [];
      };
      user_settings: {
        Row: UserSettingsRow;
        Insert: Omit<UserSettingsRow, "created_at" | "updated_at"> &
          Partial<Pick<UserSettingsRow, "created_at" | "updated_at">>;
        Update: Partial<UserSettingsRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      find_profile_by_share_code: {
        Args: { p_share_code: string };
        Returns: Pick<ProfileRow, "id" | "display_name">[];
      };
      create_scenario: {
        Args: {
          p_owner_id: string;
          p_title: string;
          p_system: string;
          p_scenario_type: "normal" | "campaign" | "kp_less";
          p_author: string;
          p_player_count_type: "fixed" | "range" | "free";
          p_player_count_fixed: number | null;
          p_player_count_min: number | null;
          p_player_count_max: number | null;
          p_player_count_text: string | null;
          p_play_time_type: "fixed" | "range" | "free";
          p_play_time_fixed: number | null;
          p_play_time_min: number | null;
          p_play_time_max: number | null;
          p_play_time_text: string | null;
        };
        Returns: string;
      };
      save_scenario_aggregate: {
        Args: {
          p_scenario_id: string;
          p_scenario: Record<string, unknown>;
          p_user_data: Record<string, unknown>;
          p_handouts: Record<string, unknown>[];
          p_episodes: Record<string, unknown>[];
          p_sessions: Record<string, unknown>[];
        };
        Returns: string;
      };
      list_scenario_shares: {
        Args: { p_scenario_id: string };
        Returns: {
          id: string;
          shared_user_id: string;
          display_name: string;
          created_at: string;
        }[];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
